const mockData = {
	regisNum: "0000",
	studentID: "640610630",
	date: "09/09//2023",
	firstName: "ณฐพงศ์",
	lastName: "พงศาวลีศรี",
	nickName: "xxx",
	birthDate: "04 ตุลาคม 2566",
	age: "20",
	Major: "Computer Engineer",
	Mentor: "Nathaphong Phongsawaleesri",
	vehicle: "Motocycle",
	vehicleType: "Honda",
	email: "nathaphong_p@cmu.ac.th",
	phone: "055-555-55555",
	money: "120000",
	houseNo: "209/9",
	village: "เพรชยนต์",
	vilNum: "8",
	district: "แม่สาย",
	road: "พหลโยธิน",
	alley: "7",
	prefacture: "แม่สาย",
	passCode: "57130",
	county: "เชียงราย",
	scholarName: [
		"Scholar championships",
		"Beatme",
		// "Hello world",
		// "nice guy",
		// "can not be help then",
		// "how to break page",
		// "it's work",
		// "how to break page",
		// "it's work",
	],
	birthYear: "2015",
	grade: "3.5",
	table: ["2001", "2015"],
	currentLevel: [1, 2, 3, 4],
};

export default mockData;
